function [ctrlWindow, controls] = MakeControlWindow
    ctrlWindow = figure('name', 'Parameter Control','NumberTitle', 'off');
    controls.kSlider = uicontrol('parent', ctrlWindow, ...
        'style','slider','units', 'normalized', ...
        'position', [0.01 0.01 0.85 0.05], ...
        'min', -10, ...
        'max', 20, ...
        'value', 0, ...
        'string', 'k', ...
        'callback', @updateControlDisplay);
    
    controls.dtSlider = uicontrol('parent', ctrlWindow, ...
        'style','slider','units', 'normalized', ...
        'position', [0.01 0.06 0.85 0.05], ...
        'min', 1e-4, ...
        'max', 0.5, ...
        'value', 1e-2, ...
        'string', 'dt', ...
        'callback', @updateControlDisplay);
    
    controls.noiseSlider = uicontrol('parent', ctrlWindow, ...
        'style','slider','units', 'normalized', ...
        'position', [0.01 0.11 0.85 0.05], ...
        'min', 0, ...
        'max', 5, ...
        'value', 0, ...
        'string', 'noise', ...
        'callback', @updateControlDisplay);
    
    controls.paramSlider = uicontrol('parent', ctrlWindow, ...
        'style','slider','units', 'normalized', ...
        'position', [0.01 0.16 0.85 0.05], ...
        'min', -10, ...
        'max', 10, ...
        'value', 1, ...
        'SliderStep', [1, 1]/20, ...
        'string', 'param', ...
        'callback', @updateControlDisplay);
    
    controls.metricSlider = uicontrol('parent', ctrlWindow, ...
        'style','slider','units', 'normalized', ...
        'position', [0.01 0.21 0.85 0.05], ...
        'min', 1, ...
        'max', 2, ...
        'value', 1, ...
        'SliderStep', [1, 1]/1, ...
        'string', {'cityblock', 'euclidean'}, ...
        'callback', @updateControlDisplay);
    
end