function [ctrlWindow, controls] = MakeControlWindow(s)
    ctrlWindow = figure('name', 'Parameter Control','NumberTitle', 'off');
    controls.kSlider = uicontrol('parent', ctrlWindow, ...
        'style','slider','units', 'normalized', ...
        'position', [0.01 0.01 0.85 0.05], ...
        'min', -10, ...
        'max', 20, ...
        'value', s.k, ...
        'tag', 'k', ...
        'callback', @updateControlDisplay);
    
    controls.dtSlider = uicontrol('parent', ctrlWindow, ...
        'style','slider','units', 'normalized', ...
        'position', [0.01 0.06 0.85 0.05], ...
        'min', 1e-4, ...
        'max', 0.5, ...
        'value', s.dt, ...
        'tag', 'dt', ...
        'callback', @updateControlDisplay);
    
    controls.noiseSlider = uicontrol('parent', ctrlWindow, ...
        'style','slider','units', 'normalized', ...
        'position', [0.01 0.11 0.85 0.05], ...
        'min', 0, ...
        'max', 5, ...
        'value', s.noise, ...
        'tag', 'noise', ...
        'callback', @updateControlDisplay);
    
    controls.paramSlider = uicontrol('parent', ctrlWindow, ...
        'style','slider','units', 'normalized', ...
        'position', [0.01 0.16 0.85 0.05], ...
        'min', -10, ...
        'max', 10, ...
        'value',s.funParams, ...
        'SliderStep', [1, 1]/20, ...
        'tag', 'param', ...
        'callback', @updateControlDisplay);
    
    controls.metricSlider = uicontrol('parent', ctrlWindow, ...
        'style','slider','units', 'normalized', ...
        'position', [0.01 0.21 0.85 0.05], ...
        'min', 1, ...
        'max', 10, ...
        'value', s.metric, ...
        'SliderStep', [0.1,1]/9, ...
        'tag', 'metric', ...
        'callback', @updateControlDisplay);
    
    funArray = GetSpatialFunctions;
    controls.funSlider = uicontrol('parent', ctrlWindow, ...
        'style','slider','units', 'normalized', ...
        'position', [0.01 0.26 0.85 0.05], ...
        'min', 1, ...
        'max', length(funArray), ...
        'value', 1, ...
        'SliderStep', [1,1]/(length(funArray)-1), ...
        'string', funArray, ...
        'tag', 'fun', ...
        'callback', @updateControlDisplay);
    
end